---
title: Gold Consulting
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Vállalkozásfejlesztés, projektgenerálás és forrásteremtés egy helyen
url: http://goldconsulting.eu
cover: "/assets/cover.png"
logo: "/assets/logo.png"
include:
- _pages
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
markdown: kramdown
permalink: "/:categories/:title"
